require:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  Exclude:
    - 'worktrees/**/*'

Style/Documentation:
  Enabled: false
